services:
  app:
    build: .
    container_name: flocker
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/ttyACM0:/dev/ttyACM0"
